# Generated by Django 4.2.7 on 2023-12-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sell', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('currency_type', models.SmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro')], default=1)),
                ('source', models.CharField(max_length=254)),
            ],
        ),
    ]
