# Generated by Django 4.2.7 on 2024-01-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='code_name',
            field=models.CharField(max_length=64, verbose_name='Code name'),
        ),
    ]
