# Generated by Django 4.2.7 on 2023-12-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_contactus_alter_rate_buy_alter_rate_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256, verbose_name='Path')),
                ('request_method', models.CharField(max_length=256, verbose_name='Request Method')),
                ('time', models.DecimalField(decimal_places=14, max_digits=19, verbose_name='Time')),
            ],
        ),
    ]
